version: "3.3"
services:
  load-data:
    image: neo4j:latest
    tty: true
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    working_dir: /data
    entrypoint: # Override open source container entrypoint to load dummy test data into the local neo4j image.
      - sh
      - -c
      - '[ -f graph.db.dump ] && (/var/lib/neo4j/bin/neo4j-admin load --from=/data/graph.db.dump --database=graph.db --force)'

  clean-data:
    image: neo4j:latest
    tty: true
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    working_dir: /data
    entrypoint: # Override open source container entrypoint to remove dummy test data from the local neo4j image.
      - sh
      - -c
      - '[ -d databases ] && (rm -rf databases)'

  neo4j:
    image: neo4j:latest
    tty: true
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins

  test:
    image: shufo/phoenix:latest
    tty: true
    entrypoint: # Override open source container entrypoint to run tests
      - sh
      - -c
      - mix hex.repo set hexpm --url $HEX_CDN && mix deps.get && mix test
    environment: # Set backup environment variables
      - NEO4J_HOST=neo4j
      - HEX_UNSAFE_HTTPS=1
      - HEX_CDN
      - HEX_MIRROR
    volumes:
      - .:/app
    working_dir: /app

  docs:
    image: shufo/phoenix:latest
    tty: true
    entrypoint: # Override open source container entrypoint to generate docs
      - sh
      - -c
      - mix hex.repo set hexpm --url $HEX_CDN && mix deps.get && mix docs
    environment: # Set backup environment variables
      - NEO4J_HOST=neo4j
      - HEX_UNSAFE_HTTPS=1
      - HEX_CDN
      - HEX_MIRROR
    volumes:
      - .:/app
    working_dir: /app

  service:
    image: shufo/phoenix:latest
    tty: true
    entrypoint: # Override open source container entrypoint which is incorrect and missing config
      - sh
      - -c
      - mix hex.repo set hexpm --url $HEX_CDN && mix deps.get && mix phx.server
    environment: # Set backup environment variables
      - NEO4J_HOST=neo4j
      - HEX_UNSAFE_HTTPS=1
      - HEX_CDN
      - HEX_MIRROR
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - neo4j
    links:
      - neo4j
